### ISSUE TITLE
Program freezes when debug callback should be called

### ISSUE THREAD

**Issue by Rotaerk** [Rotaerk/vulkanTest#1]
Currently, as of 470ff6b2574bedaac0d2faa5da9ade9819a3e85e, I have implemented a deliberate misconfiguration of swapchain creation.  According to vulkan-tutorials.com, this should trigger a complaint from the validation layer.  If I run vulkanTest with NDEBUG set, which turns off validation layers, the program exits with an error indicating that the creation of the swapchain failed.  However, if I leave the validation layers on, the output reports that the debug callback was successfully created, and then at the point where it should be called during swapchain creation, the program becomes unresponsive.

@achirkin, have you done any testing of validation layers with your bindings?  I can't find anything wrong with my code.  The only thing I can imagine is there's something wrong with the function pointer ...  And if that's the case, I have no idea how to begin to diagnose that.

Relevant sections of the code:
https://github.com/Rotaerk/vulkanTest/blob/470ff6b2574bedaac0d2faa5da9ade9819a3e85e/src/Main.hs#L58
https://github.com/Rotaerk/vulkanTest/blob/470ff6b2574bedaac0d2faa5da9ade9819a3e85e/src/Main.hs#L166-L192
https://github.com/Rotaerk/vulkanTest/blob/470ff6b2574bedaac0d2faa5da9ade9819a3e85e/src/Main.hs#L412-L427

**Comment by achirkin** [comment]
Hi @Rotaerk,

This clearly is a problem with blocking during an unsafe FFI. When you call an `unsafe` imported function in GHC, the whole capability is paused; if that function calls back to haskell, the program is blocked indefinitely (check [caution here](https://wiki.haskell.org/GHC/Using_the_FFI#Improving_efficiency), for example). 
This is what happens when you give your custom callbacks to vulkan and it tries to execute them on every vulkan call.

In `vulkan-api`, I make default versions of all functions `unsafe`, and provide `vkXxSafe` versions of functions that are `safe` imports. My fault: probably, I should have made `safe` to be default.

In your example, I changed all vulkan calls to `vkXxxSafe` and it broke gracefully instead of hanging forever. Thus, I would suggest to keep all vulkan calls that are off critical paths to be safe, and the rest be created using some helper function like following:
```Haskell
vkGetInstanceProc' :: forall proc. VulkanProc proc => VkInstance -> IO (VkProcType proc)
#ifndef NDEBUG
vkGetInstanceProc' = vkGetInstanceProcSafe @proc
#else
vkGetInstanceProc' = vkGetInstanceProc @proc
#endif
```

**Comment by Rotaerk** [comment]
Ahh, thanks @achirkin, that makes perfect sense!  I'd forgotten about how unsafe FFI calls behave.  Replacing vkCreateSwapchainKHR witth vkCreateSwapchainKHRSafe fixed the issue.

As for my thoughts on default behavior...

If the only callbacks Vulkan used were debug callbacks, then I think it would make sense to use safe by default when debugging, and unsafe by default when building for release, since the only time Vulkan would be calling Haskell is when the programmer screwed up and the validation layers complained.

However, there is at least one other context in which callbacks might occur:  allocation callbacks.  I was told that these are only going to be used on platforms with memory constraints, but on such platforms, if you're using allocation callbacks, I would think you would want everything to be safe by default, even in release.

I'm not aware of any _other_ callbacks being used in Vulkan, though I could be wrong.

The approach that makes the most sense to me is that you would define explicit vkXxxSafe and vkXxxUnsafe functions, and then have a vkXxx alias that points to one or the other.  Then, just like you did with NATIVE_FFI_VK_VERSION_1_0 and such, have a setting that determines whether these aliases point to the safe or unsafe versions.  In some cases it might be convenient to be able to toggle between safe/unsafe based on NDEBUG, rather than having to set both NDEBUG *and* your safe/unsafe setting, but it probably shouldn't be inescapably bound to that...

This approach would allow the programmer to use the standard Vulkan function names through the majority of their code, to configure whether they want these to be safe/unsafe by default, and to override the default for individual calls by using the explicit Safe and Unsafe variants.
